Vagrant.configure("2") do |config|
    config.vm.synced_folder ".", "/vagrant"
    config.vm.define :client do |client|
      client.vm.box = "ubuntu/bionic64"
      client.vm.network :private_network, ip: "10.0.0.2"
      client.vm.hostname = "client.local"
    end  
  end
