Vagrant.configure("2") do |config|
  
  config.vm.network "forwarded_port", guest: 80, host: 8088
  
  config.vm.define "web" do |web|
      web.vm.box = "ubuntu/bionic64"
      web.vm.hostname = 'web'
  end

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "playbook.yml"
    ansible.raw_arguments  = "--ask-vault-pass"
  end

end